//Event Types
export const UPLOAD_PITCURE = "UPLOAD_PITCURE";
export const UPLOAD_PITCURE_SUCCESS = "UPLOAD_PITCURE_SUCCESS";
export const UPLOAD_PITCURE_FAIL = "UPLOAD_PITCURE_FAIL";

//Login
export const LOGIN = "LOGIN";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

//User
export const GET_USER_DETAILS = "GET_USER_DETAILS";
export const GET_USER_DETAILS_SUCCESS = "GET_USER_DETAILS_SUCCESS";
export const GET_USER_DETAILS_FAIL = "GET_USER_DETAILS_FAIL";

export const CREATE_USER = "CREATE_USER";
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";
export const CREATE_USER_FAIL = "CREATE_USER_FAIL";
export const RESET_AUTH = "RESET_AUTH";

//Profile
export const PATCH_USER_DETAILS = "PATCH_USER_DETAILS";
export const PATCH_USER_DETAILS_SUCCESS = "PATCH_USER_DETAILS_SUCCESS";
export const PATCH_USER_DETAILS_FAILURE = "PATCH_USER_DETAILS_FAILURE";

export const UPDATE_USER_DETAILS = "UPDATE_USER_DETAILS";
export const UPDATE_USER_DETAILS_SUCCESS = "UPDATE_USER_DETAILS_SUCCESS";
export const UPDATE_USER_DETAILS_FAILURE = "UPDATE_USER_DETAILS_FAILURE";
